### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by gauchotche** [dewiniaid/BlueprintExtensions#11]
Getting this non-recoverable error after last update... wasn't happening.

![blueprint_error](https://user-images.githubusercontent.com/33750853/55554090-4ef28a80-56b8-11e9-8884-142fd9daa558.jpg)

**Comment by dewiniaid** [comment]
What version of Factorio were you running at the time?

The Landfill module of BlueprintExtensions relies on a feature added in 0.17.22.  If you're unable to update, you'll want to use BlueprintExtensions 0.3.2 or earlier which doesn't have the Landfill module.

**Comment by dewiniaid** [comment]
I'm unable to reproduce this in the current 0.17 experimentals.  I'm guessing from your screenshot that you're running 0.17.14, which won't work with any version of Blueprint Extensions >= 0.4.0

The new version of Blueprint Extensions now properly depends on `base >= 0.17.22` rather than just `base >= 0.17`, which should eliminate this confusion in the future.
