### ISSUE TITLE
BP Extention Buttons compete with FARL for screenspace, preventing FARL use.

### ISSUE THREAD

**Issue by PiggyWhiskey** [dewiniaid/BlueprintExtensions#13]
BP Extentions have vertical stacked buttons, which forces other GUI's to be below it.
FARL has a large GUI, and when forced lower, the bottom buttons are un-usable (Reading BP)

This is only if FARL's GUI is loaded after yours.

Request:
a) Change to Horizontal stacked buttons.
b) Toggle option to disable Buttons

Edit: Temporary solution is to lower Interface Size to 75% to fit both GUI's within the usable area.

**Comment by dewiniaid** [comment]
BPEX uses the standard mod gui flows (namely `mod_gui.get_frame_flow`), which define a common 'top' area for icons and a 'left' area for panels.  Since the icons are only displayed when in context, it opts to use a vertical panel instead of permanently cluttering the top icon bar.  If this panel was horizontal, it'd shift everything else out to the right 

However, multiple visible panels are arranged horizontally... so if FARL is showing above/below it then this suggests FARL is not using the standard mod gui.  The problem probably lies in FARL, then, though I've yet to take a look and confirm that.

You already can disable the buttons: Settings -> Mod Settings -> Per Player -> Blueprint Extensions -> uncheck all of the "Show buttons" options.

**Comment by dewiniaid** [comment]
Confirmed with Choumiko that updating FARL to use the mod gui is probably in the works, so that should resolve this.
